CREATE TABLE `role` (
    `id` BIGINT AUTO_INCREMENT,
    `parent_id` BIGINT NOT NULL,
    `role_name` VARCHAR(128) NOT NULL DEFAULT '' UNIQUE,
    `description` VARCHAR(255) NOT NULL DEFAULT '',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `delete_at` TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `status` INT NOT NULL DEFAULT '1',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB;
