// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type CreateRequest struct {
	ParentId  int64  `json:"parent_id"`
	MenuName  string `json:"menu_name"`
	Path      string `json:"path"`
	Method    string `json:"method"`
	Icon      string `json:"icon"`
	SortOrder int32  `json:"sort_order"`
	Status    int32  `json:"status"`
}

type CreateResponse struct {
	Id int64 `json:"id"`
}

type UpdateRequest struct {
	ParentId  int64  `json:"parent_id"`
	MenuName  string `json:"menu_name"`
	Path      string `json:"path"`
	Method    string `json:"method"`
	Icon      string `json:"icon"`
	SortOrder int32  `json:"sort_order"`
	Status    int32  `json:"status"`
}

type UpdateResponse struct {
	Id        int64  `json:"id"`
	ParentId  int64  `json:"parent_id"`
	MenuName  string `json:"menu_name"`
	Path      string `json:"path"`
	Method    string `json:"method"`
	Icon      string `json:"icon"`
	SortOrder int32  `json:"sort_order"`
	Status    int32  `json:"status"`
}
