// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	"zore/service/menu/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/menu/create",
				Handler: CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/menu/update/:id",
				Handler: UpdateHandler(serverCtx),
			},
		},
	)
}
