// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type CreateRequest struct {
	ParentId     int64   `json:"parent_id"`
	RoleName     string  `json:"role_name"`
	Description  string  `json:"description"`
	Status       int64   `json:"status"`
	PermissionId []int64 `json:"permission_id"`
}

type CreateResponse struct {
	Id int64 `json:"id"`
}
