// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"
	"user-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/create",
				Handler: CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/list",
				Handler: ListHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/user/login",
				Handler: DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/logout",
				Handler: LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/update/:id",
				Handler: UpdateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/login",
				Handler: LoginHandler(serverCtx),
			},
		},
	)
}
