// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type CreateRequest struct {
	ParentId int64   `json:"parent_id"`
	Username string  `json:"username"`
	Password string  `json:"password"`
	Status   int64   `json:"status"`
	RoleId   []int64 `json:"role_id"`
}

type CreateResponse struct {
	Id int64 `json:"id"`
}

type DeleteRequest struct {
	Id uint64 `json:"id"`
}

type DeleteResponse struct {
}

type ListRequest struct {
	Username *string `form:"username,optional"`
	Status   *int64  `form:"status,optional"`
	Page     int64   `form:"page"`
	PageSize int64   `form:"page_size"`
}

type ListResponse struct {
	List     []UserItem `json:"list"`
	Page     int64      `json:"page"`
	PageSize int64      `json:"page_size"`
	Count    int64      `json:"count"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	Username     string `json:"username"`
}

type LogoutRequest struct {
}

type LogoutResponse struct {
}

type Role struct {
	Id       uint64 `json:"id"`
	ParentId uint64 `json:"parent_id"`
	RoleName string `json:"role_name"`
}

type UpdateRequest struct {
	Id       int64   `path:"id"`
	ParentId int64   `json:"parent_id"`
	Password *string `json:"password"`
	Status   *int64  `json:"status"`
	RoleId   []int64 `json:"role_id"`
}

type UpdateResponse struct {
	Id       uint64  `json:"id"`
	ParentId int64   `json:"parent_id"`
	Username string  `json:"username"`
	Password string  `json:"password"`
	RoleId   []int64 `json:"role_id"`
}

type UserItem struct {
	Id        uint64 `json:"id"`
	ParentId  int64  `json:"parent_id"`
	Username  string `json:"username"`
	Password  string `json:"password"`
	Status    int64  `json:"status"`
	Ip        string `json:"ip"`
	LoginLast int64  `json:"login_last"`
	Role      []Role `json:"role"`
}
